# Site settings
title: Commcare XForm Specification
email: 
description: "Documents the XForm and OpenRosa-derived form specification as supported in CommCare."
baseurl: ""
url: ""

# Build settings
markdown: kramdown
safe: true
highlighter: pygments
collections:
- sections
